version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1400:1433"
    environment:
      SA_PASSWORD: "SenhaF0rt&"
      ACCEPT_EULA: "Y"
    restart: always
  #back-end:
  #  container_name: back-end
  #  image: pispring
  #  ports:
  #    - "80:80"
  #  links:
  #    - "sql-server-db:sql-server-db"
  #  restart: always
